import React from 'react';
import type { LogSegment } from '../constants/types';
import { STATUS_Y } from '../constants/types';

interface Props {
  segments: LogSegment[];
  day: number;
  date: string;
  driverName: string;
  carrierName: string;
}

export const ELDLogSheet: React.FC<Props> = ({ segments, day, date, driverName, carrierName }) => {
  const chartWidth = 760;
  const hourWidth = chartWidth / 24;

  // Calcul des totaux par ligne
  const getSum = (status: string) => 
    segments.filter(s => s.status === status).reduce((a, b) => a + b.duration, 0).toFixed(1);

  // Extraction des remarques (ex: Pickup, Fuel, etc.)
  const remarks = segments.filter(s => s.label !== 'Driving');

  return (
    <div className="bg-white p-6 shadow-2xl rounded-xl border border-gray-300 mb-12 w-[850px] mx-auto">
      <div className="relative border-2 border-black" style={{ width: '800px', height: '500px' }}>
        {/* L'image de fond fournie */}
        <img src="/blank-paper-log.png" className="absolute inset-0 w-full h-full object-fill" alt="Log Sheet" />
        
        {/* --- 1. CHAMPS TEXTES (DATE, NOM, CARRIER) --- */}
        <div className="absolute top-[45px] left-[60px] font-mono text-sm text-blue-800 font-bold uppercase">
          {date}
        </div>
        <div className="absolute top-[45px] left-[350px] font-mono text-sm text-blue-800 font-bold uppercase">
          {driverName}
        </div>
        <div className="absolute top-[75px] left-[60px] font-mono text-xs text-blue-800 font-bold uppercase">
          {carrierName}
        </div>

        {/* --- 2. GRAPHIQUE SVG (LIGNES ROUGES) --- */}
        <svg className="absolute top-[125px] left-[32px] w-[736px] h-[140px]">
          {segments.map((seg, i) => {
            const x1 = seg.start_hour * hourWidth;
            const x2 = x1 + (seg.duration * hourWidth);
            const y = STATUS_Y[seg.status] - 10; // Ajustement Y selon ta grille
            const next = segments[i + 1];

            return (
              <g key={i}>
                {/* Ligne horizontale de statut */}
                <line x1={x1} y1={y} x2={x2} y2={y} stroke="#d00" strokeWidth="2.5" />
                {/* Ligne verticale de transition */}
                {next && <line x1={x2} y1={y} x2={x2} y2={STATUS_Y[next.status] - 10} stroke="#d00" strokeWidth="2.5" />}
              </g>
            );
          })}
        </svg>

        {/* --- 3. TOTAUX HORAIRES (COLONNE DE DROITE) --- */}
        <div className="absolute top-[148px] right-[28px] flex flex-col gap-[14px] font-mono text-red-700 font-bold text-sm">
            <span>{getSum('OFF_DUTY')}</span>
            <span>{getSum('SLEEPER')}</span>
            <span>{getSum('DRIVING')}</span>
            <span>{getSum('ON_DUTY')}</span>
        </div>

        {/* --- 4. REMARQUES (L'ENDROIT OÙ ÇA S'EST PASSÉ) --- */}
        <div className="absolute top-[320px] left-[40px] w-[720px] h-[150px] flex flex-col gap-1">
          <h4 className="text-[10px] font-bold text-gray-400 mb-1">REMARKS / STOPS:</h4>
          {remarks.map((r, i) => (
            <div key={i} className="flex justify-between border-b border-gray-100 text-[11px] font-mono text-blue-900">
              <span>{r.label}</span>
              <span>Start: {r.start_hour.toFixed(1)}h</span>
            </div>
          ))}
        </div>
      </div>

      <div className="mt-2 text-[9px] text-gray-400 italic text-right">
        Generated by Spotter Compliance Engine v1.0 - Day {day}
      </div>
    </div>
  );
};